--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."EMPLOYEE" 
   (	"EMP_NO" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"POSITION" VARCHAR2(30 BYTE), 
	"DEPARTMENT" VARCHAR2(50 BYTE), 
	"SALARY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCOTT.EMPLOYEE
SET DEFINE OFF;
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (1,'강병헌','과장','인사팀',4800);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (2,'김동수','대리','인사팀',2700);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (3,'김시우','과장','총무팀',4500);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (4,'김준래','대리','인사팀',3200);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (5,'박셩우','대리','총무팀',3400);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (6,'박병상','부장','총무팀',6400);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (7,'박정현','과장','경영지원팀',4400);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (8,'서민우','차장','경영지원팀',5100);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (9,'이동희','대리','영업팀',2800);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (10,'이원구','과장','영업팀',3200);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (11,'정성수','주임','영업팀',2400);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (12,'정희우','과장','전산팀',4500);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (13,'조성수','사원','전산팀',2400);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (14,'주지우','사원','경영지원팀',2200);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (15,'최승수','주임','전산팀',2600);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (16,'한상오','과장','구매팀',4300);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (17,'이지원','사원','구매팀',2000);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (18,'김희연','주임','구매팀',2300);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (19,'노소정','사원','인사팀',2200);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (20,'손지해','주임','인사팀',2500);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (21,'정다혜','과장','전산팀',3600);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (22,'장세이','사원','경영지원팀',2600);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (23,'차영연','주임','전산팀',2300);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (24,'장희은','사원','구매팀',2000);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (25,'남혜미','주임','구매팀',2300);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (26,'유민주','사원','구매팀',2200);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (27,'원소은','주임','인사팀',2500);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (33,'홍길동','과장','인사팀',5000);
Insert into SCOTT.EMPLOYEE (EMP_NO,NAME,POSITION,DEPARTMENT,SALARY) values (45,'김슬기','대리','총무팀',3200);
--------------------------------------------------------
--  DDL for Index SYS_C007042
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C007042" ON "SCOTT"."EMPLOYEE" ("EMP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."EMPLOYEE" ADD PRIMARY KEY ("EMP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
