SELECT INITCAP('the soap') FROM DUAL; -- 단어별 첫글자 대문자화
SELECT LOWER('TEST ORACLE') FROM DUAL; -- 단어를 전부 소문자화
SELECT UPPER('Test Oracle') FROM DUAL; -- 단어를 전부 대문자화
SELECT LENGTH('안녕하세요'), LENGTH('HELLO'), LENGTH('12334') FROM DUAL;--글자 개수
SELECT LENGTHB('안녕하세요'), LENGTHB('HELLO'), LENGTHB('12334') FROM DUAL;--바이트 개수
SELECT CONCAT('A','BCD'), 'A' || 'BCD' FROM DUAL; --문자열 붙이기
SELECT CONCAT('A','BCD'), 'A' || 'BCD'||1234 FROM DUAL; --문자열 붙이기
SELECT SUBSTR('ABCDEFG',3,3) FROM DUAL; --문자열 부분 추출, 글자 위치, 가져올 개수
SELECT SUBSTR('안녕하세요',2,3) FROM DUAL;
SELECT SUBSTRB('안녕하세요',1,4) FROM DUAL;
SELECT INSTR('ABCDEFG', 'CD') FROM DUAL; --해당 단어 위치 출력
SELECT INSTR('ABCDEFG', 'ZZ') FROM DUAL; --해당 단어 위치 출력, 없으면 0이 출력
SELECT INSTR('HELLO WORLD', ' ') FROM DUAL; -- 중간에 공백 체크 할때
SELECT INSTR('HELLOWORLD', ' ') FROM DUAL;
SELECT LPAD('HELLO',10,'*'), RPAD('HELLO',10,'*') FROM DUAL;
SELECT LPAD('HELLO',10,'*%+'), RPAD('HELLO',10,'*%+') FROM DUAL;
SELECT LPAD('HELLO',10,1234567890), RPAD('HELLO',10,1234567890) FROM DUAL;
SELECT LTRIM('AAAAFSDSFDFAAAA','A'), RTRIM('AAAAADXFCDFGAAAA','A') FROM DUAL;
SELECT TRIM('      ASDASD    '),LENGTH(TRIM('      ASDASD    ')),
LENGTH('      ASDASD    ') FROM DUAL;
SELECT REPLACE('AAAADFGGDFG','A','12') FROM DUAL;
--자리수 제어
SELECT ROUND(567.456,2),ROUND(567.456,0),ROUND(567.456,-1) FROM DUAL;
SELECT TRUNC(567.456,2),TRUNC(567.456,0),TRUNC(567.456,-1) FROM DUAL;
-- CEIL은 올림 처리, FLOOR 내림
SELECT CEIL(123.156), FLOOR(123.456) FROM DUAL;

SELECT POWER(2,10), MOD(5,3) FROM DUAL;
--날짜/시간
SELECT SYSDATE FROM DUAL;
--DB 날짜 형식 바꿈
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH:MI:SS';
ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';
SELECT MONTHS_BETWEEN(SYSDATE,'20/12/25') FROM DUAL;
SELECT SYSDATE - TO_DATE('20/12/25','YY/MM/DD') FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,3) FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'화') FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;
--형변환
SELECT 2 + 2, 2 + '2' FROM DUAL;
SELECT TO_NUMBER('1234') * 2 FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YYYY'),
TO_CHAR(SYSDATE,'YY'),TO_CHAR(SYSDATE,'RRRR'),TO_CHAR(SYSDATE,'RR'),
TO_CHAR(SYSDATE,'YEAR') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'MM'),TO_CHAR(SYSDATE,'MON'),TO_CHAR(SYSDATE,'MONTH')
    FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DD'),TO_CHAR(SYSDATE,'DAY'),TO_CHAR(SYSDATE,'DDTH')
    FROM DUAL;

SELECT POSITION, DECODE(POSITION, 4, '보너스 대상자') FROM EMPLOYEE;
SELECT POSITION, DECODE(POSITION, 4, '보너스 대상자','대상자 아님') FROM EMPLOYEE;
SELECT POSITION, DECODE(POSITION, 4, '보너스 대상자',5, '휴가대상자','대상자 아님') FROM EMPLOYEE;








